"""Update contractor invoices schema to match requirements

Revision ID: bd38bc408fa1
Revises: f17dfaf1280e
Create Date: 2026-02-02 23:05:17.166755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd38bc408fa1'
down_revision: Union[str, Sequence[str], None] = 'f17dfaf1280e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contractor_invoice_details', sa.Column('deleted_flag', sa.Boolean(), nullable=False))
    op.add_column('contractor_invoices', sa.Column('tax_rate_id', sa.Integer(), nullable=False))
    op.add_column('contractor_invoices', sa.Column('total_discount_amount', sa.Integer(), nullable=False))
    op.add_column('contractor_invoices', sa.Column('total_after_discount', sa.Integer(), nullable=False))
    op.add_column('contractor_invoices', sa.Column('payment_due_date', sa.Date(), nullable=True))
    op.add_column('contractor_invoices', sa.Column('payment_term', sa.String(length=200), nullable=True))
    op.add_column('contractor_invoices', sa.Column('deleted_flag', sa.Boolean(), nullable=False))
    op.alter_column('contractor_invoices', 'invoice_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_foreign_key(None, 'contractor_invoices', 'tax_rates', ['tax_rate_id'], ['id'])
    op.drop_column('contractor_invoices', 'receipt_date')
    op.drop_column('contractor_invoices', 'invoice_number')
    op.drop_column('contractor_invoices', 'end_date')
    op.drop_column('contractor_invoices', 'start_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contractor_invoices', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('contractor_invoices', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('contractor_invoices', sa.Column('invoice_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('contractor_invoices', sa.Column('receipt_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contractor_invoices', type_='foreignkey')
    op.alter_column('contractor_invoices', 'invoice_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('contractor_invoices', 'deleted_flag')
    op.drop_column('contractor_invoices', 'payment_term')
    op.drop_column('contractor_invoices', 'payment_due_date')
    op.drop_column('contractor_invoices', 'total_after_discount')
    op.drop_column('contractor_invoices', 'total_discount_amount')
    op.drop_column('contractor_invoices', 'tax_rate_id')
    op.drop_column('contractor_invoice_details', 'deleted_flag')
    # ### end Alembic commands ###
