"""add_invoice_fields

Revision ID: e719581c8f23
Revises: 087a55338e39
Create Date: 2026-01-26 01:22:49.364429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e719581c8f23'
down_revision: Union[str, Sequence[str], None] = '087a55338e39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_contractor_invoices_id'), 'contractor_invoices', ['id'], unique=False)
    op.drop_column('contractor_invoices', 'created_at')
    op.drop_column('contractor_invoices', 'updated_at')
    op.create_index(op.f('ix_contractors_id'), 'contractors', ['id'], unique=False)
    op.drop_index(op.f('idx_delivery_note_details_delivery_note'), table_name='delivery_note_details')
    op.create_index(op.f('ix_delivery_note_details_id'), 'delivery_note_details', ['id'], unique=False)
    op.alter_column('delivery_notes', 'delivery_date',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('delivery_notes', 'billing_date',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('delivery_notes', 'image_recognition_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_delivery_notes_date'), table_name='delivery_notes')
    op.drop_index(op.f('idx_delivery_notes_sales_person'), table_name='delivery_notes')
    op.create_index(op.f('ix_delivery_notes_id'), 'delivery_notes', ['id'], unique=False)
    op.create_index(op.f('ix_discount_rates_id'), 'discount_rates', ['id'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.add_column('sales_invoices', sa.Column('invoice_date', sa.Date(), nullable=True))
    op.add_column('sales_invoices', sa.Column('receipt_date', sa.Date(), nullable=True))
    op.add_column('sales_invoices', sa.Column('non_discountable_amount', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('sales_invoices', sa.Column('note', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_sales_persons_id'), 'sales_persons', ['id'], unique=False)
    op.create_index(op.f('ix_tax_rates_id'), 'tax_rates', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_tax_rates_id'), table_name='tax_rates')
    op.drop_index(op.f('ix_sales_persons_id'), table_name='sales_persons')
    op.drop_column('sales_invoices', 'note')
    op.drop_column('sales_invoices', 'non_discountable_amount')
    op.drop_column('sales_invoices', 'receipt_date')
    op.drop_column('sales_invoices', 'invoice_date')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_discount_rates_id'), table_name='discount_rates')
    op.drop_index(op.f('ix_delivery_notes_id'), table_name='delivery_notes')
    op.create_index(op.f('idx_delivery_notes_sales_person'), 'delivery_notes', ['sales_person_id'], unique=False)
    op.create_index(op.f('idx_delivery_notes_date'), 'delivery_notes', ['delivery_date'], unique=False)
    op.alter_column('delivery_notes', 'image_recognition_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('delivery_notes', 'billing_date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('delivery_notes', 'delivery_date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_index(op.f('ix_delivery_note_details_id'), table_name='delivery_note_details')
    op.create_index(op.f('idx_delivery_note_details_delivery_note'), 'delivery_note_details', ['delivery_note_id'], unique=False)
    op.drop_index(op.f('ix_contractors_id'), table_name='contractors')
    op.add_column('contractor_invoices', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('contractor_invoices', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_contractor_invoices_id'), table_name='contractor_invoices')
    # ### end Alembic commands ###
