"""Create contractor invoices tables with nullable dates

Revision ID: f17dfaf1280e
Revises: d39bca618ffc
Create Date: 2026-02-02 22:25:59.615273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f17dfaf1280e'
down_revision: Union[str, Sequence[str], None] = 'd39bca618ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractor_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('discount_rate_id', sa.Integer(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('receipt_date', sa.Date(), nullable=True),
    sa.Column('non_discountable_amount', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('quota_subtotal', sa.Integer(), nullable=False),
    sa.Column('quota_discount_amount', sa.Integer(), nullable=False),
    sa.Column('quota_total', sa.Integer(), nullable=False),
    sa.Column('non_quota_subtotal', sa.Integer(), nullable=False),
    sa.Column('non_quota_discount_amount', sa.Integer(), nullable=False),
    sa.Column('non_quota_total', sa.Integer(), nullable=False),
    sa.Column('total_amount_ex_tax', sa.Integer(), nullable=False),
    sa.Column('tax_amount', sa.Integer(), nullable=False),
    sa.Column('total_amount_inc_tax', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['discount_rate_id'], ['discount_rates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contractor_invoices_id'), 'contractor_invoices', ['id'], unique=False)
    op.create_table('contractor_invoice_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractor_invoice_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contractor_invoice_id'], ['contractor_invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contractor_invoice_details_id'), 'contractor_invoice_details', ['id'], unique=False)
    op.create_index(op.f('ix_contractors_id'), 'contractors', ['id'], unique=False)
    op.drop_index(op.f('idx_delivery_note_details_delivery_note'), table_name='delivery_note_details')
    op.create_index(op.f('ix_delivery_note_details_id'), 'delivery_note_details', ['id'], unique=False)
    op.alter_column('delivery_notes', 'delivery_date',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('delivery_notes', 'billing_date',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('delivery_notes', 'image_recognition_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_delivery_notes_date'), table_name='delivery_notes')
    op.drop_index(op.f('idx_delivery_notes_sales_person'), table_name='delivery_notes')
    op.create_index(op.f('ix_delivery_notes_id'), 'delivery_notes', ['id'], unique=False)
    op.alter_column('discount_rates', 'threshold_amount',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_discount_rates_id'), 'discount_rates', ['id'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_sales_persons_id'), 'sales_persons', ['id'], unique=False)
    op.create_index(op.f('ix_tax_rates_id'), 'tax_rates', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_tax_rates_id'), table_name='tax_rates')
    op.drop_index(op.f('ix_sales_persons_id'), table_name='sales_persons')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_discount_rates_id'), table_name='discount_rates')
    op.alter_column('discount_rates', 'threshold_amount',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_delivery_notes_id'), table_name='delivery_notes')
    op.create_index(op.f('idx_delivery_notes_sales_person'), 'delivery_notes', ['sales_person_id'], unique=False)
    op.create_index(op.f('idx_delivery_notes_date'), 'delivery_notes', ['delivery_date'], unique=False)
    op.alter_column('delivery_notes', 'image_recognition_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('delivery_notes', 'billing_date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('delivery_notes', 'delivery_date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_index(op.f('ix_delivery_note_details_id'), table_name='delivery_note_details')
    op.create_index(op.f('idx_delivery_note_details_delivery_note'), 'delivery_note_details', ['delivery_note_id'], unique=False)
    op.drop_index(op.f('ix_contractors_id'), table_name='contractors')
    op.drop_index(op.f('ix_contractor_invoice_details_id'), table_name='contractor_invoice_details')
    op.drop_table('contractor_invoice_details')
    op.drop_index(op.f('ix_contractor_invoices_id'), table_name='contractor_invoices')
    op.drop_table('contractor_invoices')
    # ### end Alembic commands ###
